#
#  This file is part of the Jikes RVM project (http://jikesrvm.org).
#
#  This file is licensed to You under the Common Public License (CPL);
#  You may not use this file except in compliance with the License. You
#  may obtain a copy of the License at
#
#      http://www.opensource.org/licenses/cpl1.0.php
#
#  See the COPYRIGHT.txt file distributed with this work for information
#  regarding copyright ownership.
#

# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 42) do

  create_table "audit_logs", :force => true do |t|
    t.column "name",       :string,   :limit => 120, :null => false
    t.column "created_at", :datetime,                :null => false
    t.column "user_id",    :integer
    t.column "username",   :string,   :limit => 40
    t.column "ip_address", :string,   :limit => 24
    t.column "message",    :text,                    :null => false
  end

  add_index "audit_logs", ["created_at"], :name => "index_audit_logs_on_created_at"
  add_index "audit_logs", ["id"], :name => "index_audit_logs_on_id", :unique => true
  add_index "audit_logs", ["name"], :name => "index_audit_logs_on_name"
  add_index "audit_logs", ["name", "created_at"], :name => "index_audit_logs_on_name_and_created_at"
  add_index "audit_logs", ["user_id", "name", "created_at"], :name => "index_audit_logs_on_name_and_created_at_and_user_id"
  add_index "audit_logs", ["user_id"], :name => "index_audit_logs_on_user_id"

  create_table "build_configuration_outputs", :id => false, :force => true do |t|
    t.column "build_configuration_id", :integer, :null => false
    t.column "output",                 :text,    :null => false
  end

  add_index "build_configuration_outputs", ["build_configuration_id"], :name => "index_build_configuration_outputs_on_build_configuration_id", :unique => true

  create_table "build_configuration_params", :id => false, :force => true do |t|
    t.column "owner_id", :integer,                :null => false
    t.column "key",      :string,  :limit => 50,  :null => false
    t.column "value",    :string,  :limit => 256, :null => false
  end

  add_index "build_configuration_params", ["owner_id"], :name => "index_build_configuration_params_on_owner_id"
  add_index "build_configuration_params", ["owner_id", "key"], :name => "index_build_configuration_params_on_owner_id_and_key", :unique => true
  add_index "build_configuration_params", ["owner_id", "key", "value"], :name => "index_build_configuration_params_on_owner_id_and_key_and_value"

  create_table "build_configurations", :force => true do |t|
    t.column "test_run_id", :integer,               :null => false
    t.column "name",        :string,  :limit => 75, :null => false
    t.column "result",      :string,  :limit => 15, :null => false
    t.column "time",        :integer,               :null => false
  end

  add_index "build_configurations", ["id"], :name => "index_build_configurations_on_id", :unique => true
  add_index "build_configurations", ["test_run_id", "name"], :name => "index_build_configurations_on_test_run_id_and_name", :unique => true

  create_table "build_target_params", :id => false, :force => true do |t|
    t.column "owner_id", :integer,                :null => false
    t.column "key",      :string,  :limit => 50,  :null => false
    t.column "value",    :string,  :limit => 256, :null => false
  end

  add_index "build_target_params", ["owner_id"], :name => "index_build_target_params_on_owner_id"
  add_index "build_target_params", ["owner_id", "key"], :name => "index_build_target_params_on_owner_id_and_key", :unique => true
  add_index "build_target_params", ["owner_id", "key", "value"], :name => "index_build_target_params_on_owner_id_and_key_and_value"

  create_table "build_targets", :force => true do |t|
    t.column "name",        :string,  :limit => 75, :null => false
    t.column "test_run_id", :integer,               :null => false
  end

  add_index "build_targets", ["id"], :name => "index_build_targets_on_id", :unique => true
  add_index "build_targets", ["name"], :name => "index_build_targets_on_name"
  add_index "build_targets", ["test_run_id"], :name => "index_build_targets_on_test_run_id", :unique => true
  add_index "build_targets", ["name", "test_run_id"], :name => "index_build_targets_on_test_run_id_and_name"

  create_table "groups", :force => true do |t|
    t.column "test_configuration_id", :integer,               :null => false
    t.column "name",                  :string,  :limit => 75, :null => false
  end

  add_index "groups", ["id"], :name => "index_groups_on_id", :unique => true
  add_index "groups", ["name"], :name => "index_groups_on_name"
  add_index "groups", ["test_configuration_id", "name"], :name => "index_groups_on_test_configuration_id_and_name", :unique => true

  create_table "hosts", :force => true do |t|
    t.column "name", :string, :limit => 100, :null => false
  end

  add_index "hosts", ["id"], :name => "index_hosts_on_id", :unique => true
  add_index "hosts", ["name"], :name => "index_hosts_on_name", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "sessid",     :string,   :limit => 32, :null => false
    t.column "data",       :text
    t.column "created_on", :datetime,               :null => false
    t.column "updated_on", :datetime,               :null => false
  end

  add_index "sessions", ["id"], :name => "index_sessions_on_id", :unique => true
  add_index "sessions", ["sessid"], :name => "index_sessions_on_sessid", :unique => true

  create_table "statistics_map", :force => true do |t|
    t.column "test_run_name",            :string,  :limit => 75
    t.column "build_configuration_name", :string,  :limit => 75
    t.column "test_configuration_name",  :string,  :limit => 75
    t.column "group_name",               :string,  :limit => 75, :null => false
    t.column "test_case_name",           :string,  :limit => 75, :null => false
    t.column "statistic_key",            :string,  :limit => 50, :null => false
    t.column "name",                     :string,  :limit => 50, :null => false
    t.column "statistic_function",       :string,  :limit => 75, :null => false
    t.column "less_is_more",             :boolean,               :null => false
    t.column "label",                    :string,  :limit => 75, :null => false
  end

  add_index "statistics_map", ["build_configuration_name"], :name => "index_statistics_map_on_build_configuration_name"
  add_index "statistics_map", ["group_name"], :name => "index_statistics_map_on_group_name"
  add_index "statistics_map", ["id"], :name => "index_statistics_map_on_id", :unique => true
  add_index "statistics_map", ["statistic_key"], :name => "index_statistics_map_on_statistic_key"
  add_index "statistics_map", ["test_case_name"], :name => "index_statistics_map_on_test_case_name"
  add_index "statistics_map", ["test_configuration_name"], :name => "index_statistics_map_on_test_configuration_name"
  add_index "statistics_map", ["test_run_name"], :name => "index_statistics_map_on_test_run_name"
  add_index "statistics_map", ["test_run_name", "build_configuration_name", "test_configuration_name", "group_name", "test_case_name", "statistic_key"], :name => "index_statistics_map_on_test_run_name_and_build_configuration_n", :unique => true

  create_table "system_settings", :force => true do |t|
    t.column "name",  :string, :null => false
    t.column "value", :text,   :null => false
  end

  add_index "system_settings", ["id"], :name => "index_system_settings_on_id", :unique => true
  add_index "system_settings", ["name"], :name => "index_system_settings_on_name", :unique => true

  create_table "test_case_execution_numerical_statistics", :id => false, :force => true do |t|
    t.column "owner_id", :integer,               :null => false
    t.column "key",      :string,  :limit => 50, :null => false
    t.column "value",    :float,                 :null => false
  end

  add_index "test_case_execution_numerical_statistics", ["owner_id"], :name => "index_test_case_result_numerical_statistics_on_owner_id"
  add_index "test_case_execution_numerical_statistics", ["owner_id", "key"], :name => "index_test_case_result_numerical_statistics_on_owner_id_and_key", :unique => true
  add_index "test_case_execution_numerical_statistics", ["owner_id", "key", "value"], :name => "tcr_ns_okv_index"

  create_table "test_case_execution_outputs", :id => false, :force => true do |t|
    t.column "owner_id", :integer, :null => false
    t.column "output",   :text,    :null => false
  end

  add_index "test_case_execution_outputs", ["owner_id"], :name => "index_test_case_result_outputs_on_owner_id", :unique => true

  create_table "test_case_execution_statistics", :id => false, :force => true do |t|
    t.column "owner_id", :integer,                :null => false
    t.column "key",      :string,  :limit => 50,  :null => false
    t.column "value",    :string,  :limit => 256, :null => false
  end

  add_index "test_case_execution_statistics", ["owner_id"], :name => "index_test_case_result_statistics_on_owner_id"
  add_index "test_case_execution_statistics", ["owner_id", "key"], :name => "index_test_case_result_statistics_on_owner_id_and_key", :unique => true
  add_index "test_case_execution_statistics", ["owner_id", "key", "value"], :name => "index_test_case_result_statistics_on_owner_id_and_key_and_value"

  create_table "test_case_executions", :force => true do |t|
    t.column "name",               :string,  :limit => 75,  :null => false
    t.column "test_case_id",       :integer,                :null => false
    t.column "result",             :string,  :limit => 15,  :null => false
    t.column "result_explanation", :string,  :limit => 256, :null => false
    t.column "exit_code",          :integer,                :null => false
    t.column "time",               :integer,                :null => false
  end

  add_index "test_case_executions", ["id"], :name => "index_test_case_results_on_id", :unique => true
  add_index "test_case_executions", ["name"], :name => "index_test_case_results_on_name"
  add_index "test_case_executions", ["result"], :name => "index_test_case_results_on_result"
  add_index "test_case_executions", ["name", "test_case_id"], :name => "index_test_case_results_on_test_case_id_and_name", :unique => true

  create_table "test_case_params", :id => false, :force => true do |t|
    t.column "owner_id", :integer,                :null => false
    t.column "key",      :string,  :limit => 50,  :null => false
    t.column "value",    :string,  :limit => 256, :null => false
  end

  add_index "test_case_params", ["owner_id"], :name => "index_test_case_params_on_owner_id"
  add_index "test_case_params", ["owner_id", "key"], :name => "index_test_case_params_on_owner_id_and_key", :unique => true
  add_index "test_case_params", ["owner_id", "key", "value"], :name => "index_test_case_params_on_owner_id_and_key_and_value"

  create_table "test_case_statistics", :id => false, :force => true do |t|
    t.column "owner_id", :integer,               :null => false
    t.column "key",      :string,  :limit => 50, :null => false
    t.column "value",    :float,                 :null => false
  end

  add_index "test_case_statistics", ["owner_id"], :name => "tcn_o"
  add_index "test_case_statistics", ["owner_id", "key"], :name => "tcn_ok", :unique => true
  add_index "test_case_statistics", ["owner_id", "key", "value"], :name => "tcn_okv"

  create_table "test_cases", :force => true do |t|
    t.column "group_id", :integer,               :null => false
    t.column "name",     :string,  :limit => 75, :null => false
    t.column "command",  :text,                  :null => false
  end

  add_index "test_cases", ["group_id", "name"], :name => "index_test_cases_on_group_id_and_name", :unique => true
  add_index "test_cases", ["id"], :name => "index_test_cases_on_id", :unique => true
  add_index "test_cases", ["name"], :name => "index_test_cases_on_name"

  create_table "test_configuration_params", :id => false, :force => true do |t|
    t.column "owner_id", :integer,                :null => false
    t.column "key",      :string,  :limit => 50,  :null => false
    t.column "value",    :string,  :limit => 256, :null => false
  end

  add_index "test_configuration_params", ["owner_id"], :name => "index_test_configuration_params_on_owner_id"
  add_index "test_configuration_params", ["owner_id", "key"], :name => "index_test_configuration_params_on_owner_id_and_key", :unique => true
  add_index "test_configuration_params", ["owner_id", "key", "value"], :name => "index_test_configuration_params_on_owner_id_and_key_and_value"

  create_table "test_configurations", :force => true do |t|
    t.column "name",                   :string,  :limit => 75, :null => false
    t.column "build_configuration_id", :integer,               :null => false
  end

  add_index "test_configurations", ["build_configuration_id"], :name => "index_test_configurations_on_build_configuration_id"
  add_index "test_configurations", ["id"], :name => "index_test_configurations_on_id", :unique => true
  add_index "test_configurations", ["name"], :name => "index_test_configurations_on_name"
  add_index "test_configurations", ["name", "build_configuration_id"], :name => "index_test_configurations_on_name_and_build_configuration_id", :unique => true

  create_table "test_runs", :force => true do |t|
    t.column "name",       :string,   :limit => 75, :null => false
    t.column "variant",    :string,   :limit => 75, :null => false
    t.column "host_id",    :integer,                :null => false
    t.column "revision",   :integer,                :null => false
    t.column "start_time", :datetime,               :null => false
    t.column "end_time",   :datetime,               :null => false
    t.column "created_at", :datetime,               :null => false
  end

  add_index "test_runs", ["host_id"], :name => "index_test_runs_on_host_id"
  add_index "test_runs", ["name", "host_id", "start_time"], :name => "index_test_runs_on_host_id_and_name_and_start_time", :unique => true
  add_index "test_runs", ["id"], :name => "index_test_runs_on_id", :unique => true
  add_index "test_runs", ["name"], :name => "index_test_runs_on_name"
  add_index "test_runs", ["revision"], :name => "index_test_runs_on_revision"
  add_index "test_runs", ["start_time"], :name => "index_test_runs_on_start_time"

  create_table "users", :force => true do |t|
    t.column "username", :string,  :limit => 40, :null => false
    t.column "password", :string,  :limit => 40, :null => false
    t.column "salt",     :string,  :limit => 40, :null => false
    t.column "admin",    :boolean,               :null => false
    t.column "active",   :boolean,               :null => false
  end

  add_index "users", ["id"], :name => "users__id__idx", :unique => true
  add_index "users", ["username"], :name => "users__username__idx", :unique => true
  add_index "users", ["username", "password", "active"], :name => "users__username_and_password_and_active__idx"

  add_foreign_key "audit_logs", ["user_id"], "users", ["id"], :on_delete => :set_null, :name => "audit_logs_user_id_fkey"

  add_foreign_key "build_configuration_outputs", ["build_configuration_id"], "build_configurations", ["id"], :on_delete => :cascade, :name => "build_configuration_outputs_build_configuration_id_fkey"

  add_foreign_key "build_configuration_params", ["owner_id"], "build_configurations", ["id"], :on_delete => :cascade, :name => "build_configuration_params_owner_id_fkey"

  add_foreign_key "build_target_params", ["owner_id"], "build_targets", ["id"], :on_delete => :cascade, :name => "build_target_params_owner_id_fkey"

  add_foreign_key "groups", ["test_configuration_id"], "test_configurations", ["id"], :on_delete => :cascade, :name => "groups_test_configuration_id_fkey"

  add_foreign_key "test_case_execution_numerical_statistics", ["owner_id"], "test_case_executions", ["id"], :on_delete => :cascade, :name => "test_case_result_numerical_statistics_owner_id_fkey"

  add_foreign_key "test_case_execution_outputs", ["owner_id"], "test_case_executions", ["id"], :on_delete => :cascade, :name => "test_case_result_outputs_owner_id_fkey"

  add_foreign_key "test_case_execution_statistics", ["owner_id"], "test_case_executions", ["id"], :on_delete => :cascade, :name => "test_case_result_statistics_owner_id_fkey"

  add_foreign_key "test_case_executions", ["test_case_id"], "test_cases", ["id"], :on_delete => :cascade, :name => "test_case_results_test_case_id_fkey"

  add_foreign_key "test_case_params", ["owner_id"], "test_cases", ["id"], :on_delete => :cascade, :name => "test_case_params_owner_id_fkey"

  add_foreign_key "test_case_statistics", ["owner_id"], "test_cases", ["id"], :on_delete => :cascade, :name => "test_case_statistics_owner_id_fkey"

  add_foreign_key "test_cases", ["group_id"], "groups", ["id"], :on_delete => :cascade, :name => "test_cases_group_id_fkey"

  add_foreign_key "test_configuration_params", ["owner_id"], "test_configurations", ["id"], :on_delete => :cascade, :name => "test_configuration_params_owner_id_fkey"

  add_foreign_key "test_configurations", ["build_configuration_id"], "build_configurations", ["id"], :on_delete => :cascade, :name => "test_configurations_build_configuration_id_fkey"

  add_foreign_key "test_runs", ["host_id"], "hosts", ["id"], :on_delete => :cascade, :name => "test_runs_host_id_fkey"

end
